baseURL = "https://compassionate-edison-2dffc7.netlify.com/"
languageCode = "en-us"
title = "Colin Armstrong"
copyright = "&copy; Copyright 2020"

custom_css = "/static/css/custom.css"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "colinarms"
  github = "seeARMS"
  linkedin = "colinarms"

  # Google Analytics API key.
  ga_api_key = "Your Google Analytics tracking id"
  author = "Colin Armstrong"
  authorwebsite = "example.com"
  avatar = "https://avatars3.githubusercontent.com/u/3957773?s=460&v=4"
  contact = ""
  bio = "Google software engineer. Previously at Coinbase and Blackberry. uWaterloo alum, enjoying good â˜•ï¸ and better ðŸ·."
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = ""
  # Logo image. This is displayed ogp image.
  logo = "/path/to/logo"
  favicon = "/path/to/favicon"


[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = true

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
